sudo: required
language: r
warnings_are_errors: false
dist: trusty

r_binary_packages:
  - rjags

r_packages:
  - coda
  - covr
  - jagsUI
  - knitr
  - pROC
  - raster
  - testthat

cache:
  packages: true

after_success:
  - Rscript -e "covr::codecov()"

email:
  on_success: change
  on_failure: change
